apiVersion: tools.pongzt.com/v1alpha1
kind: GitHook
metadata:
  name: githook-sample
spec:
  gitProvider: gitlab
  eventTypes:
  - push
  - issue_comment
  - pull_request
  projectUrl: "https://gitlab.tmrnd.com.my/ahmadkarim/vote-ui.git" #replace this with your test repo
  accessToken:
    secretKeyRef:
      name: gitsecret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: gitsecret
      key: secretToken
  runspec:
    pipelineRef:
      name: build-and-deploy
    serviceAccount: default

