apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  generation: 2
  labels:
    app: vote-ui
  name: vote-ui
  namespace: vote-ui
spec:
  replicas: 1
  selector:
    app: vote-ui
    deploymentconfig: vote-ui
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: vote-ui
        deploymentconfig: vote-ui
    spec:
      containers:
        - image: >-
            image-registry.openshift-image-registry.svc:5000/vote-ui/vote-ui:latest
          imagePullPolicy: Always
          name: vote-ui
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - vote-ui
        from:
          kind: ImageStreamTag
          name: 'vote-ui:latest'
          namespace: vote-ui
        lastTriggeredImage: >-
          image-registry.openshift-image-registry.svc:5000/vote-ui/vote-ui:latest
      type: ImageChange
